"""empty message

Revision ID: 201406c5642a
Revises: 7cd817801791
Create Date: 2023-02-19 00:42:41.097954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201406c5642a'
down_revision = '7cd817801791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('dataNascimento', sa.String(length=10), nullable=False))
    op.drop_column('funcionarios', 'dataAniversario')
    op.drop_column('funcionarios', 'telefone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('telefone', sa.VARCHAR(length=150), nullable=False))
    op.add_column('funcionarios', sa.Column('dataAniversario', sa.VARCHAR(length=10), nullable=False))
    op.drop_column('funcionarios', 'dataNascimento')
    # ### end Alembic commands ###
