"""empty message

Revision ID: 9f10b31778b7
Revises: 
Create Date: 2023-03-10 02:15:30.692957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f10b31778b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=150), nullable=False),
    sa.Column('celular', sa.String(length=150), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('celular', sa.String(length=150), nullable=False),
    sa.Column('dataNascimento', sa.String(length=10), nullable=False),
    sa.Column('dataContrato', sa.String(length=10), nullable=False),
    sa.Column('funcao', sa.String(length=150), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.Column('cor', sa.String(length=150), nullable=False),
    sa.Column('placa', sa.String(length=150), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.JSON(), nullable=True),
    sa.Column('produto_id', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_atual', sa.DateTime(), nullable=True),
    sa.Column('data_agendamento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordemServico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.JSON(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordemServico')
    op.drop_table('agendamento')
    op.drop_table('orcamento')
    op.drop_table('veiculos')
    op.drop_table('usuarios')
    op.drop_table('servicos')
    op.drop_table('produtos')
    op.drop_table('funcionarios')
    op.drop_table('clientes')
    # ### end Alembic commands ###
